### ISSUE TITLE
rbfi: option for zero-weights outside outer circles

### ISSUE THREAD

**Issue by nesdnuma** [CNMAT/CNMAT-Externs#113]
Hello,

I've had a look at the "weights with null" tab in rbfi's helpfile but the weights are not at zero outside the outer circles. It would be nice to have this feature as an option.

**Comment by equilet** [comment]
Not going to happen, sorry.  If you move the outer circles closer in towards the inner, you can get very close to zero, but because of the way the math is calculated, the user does not have control over that particular variable.  You could possibly detect a very small number threshold and fade out if you like.  If this is in use for mixing, you can easily convince the ear that audio sources have gone silent.

**Comment by nesdnuma** [comment]
OK, thanks for the suggestion.
