### ISSUE TITLE
64-bit windows builds

### ISSUE THREAD

**Issue by Splatatat** [CNMAT/CNMAT-Externs#59]
I hope this is the correct place to file a request for a x64 build of OSCRoute.  This object is a dependency in many patches out there in the wild (and even gets a mention in C74 help), including the growing community for Musebots.  With 64 bit computing becoming the norm, it will save time for many to create an x64 win build of this.  I understand this is a convenience object. Please let me know if there's other suitable work arounds.  I would like to see all CNMAT externals built for x64 win!  Thank you!

**Comment by equilet** [comment]
@Splatatat  - yes, this is in our issue queue.

The problem is that my build sys for Win externals got screwed up a bit and we'll need to revisit it after our summer courses occur.  As you found in your FB thread, we're planning on addressing it in Sept or Oct at the latest.

FWIW, o.route replaces osc-route and should be migrated to asap.

**Comment by Splatatat** [comment]
I have found an x64 build of OSCRoute for Windows! (and some others)

http://www.sfu.ca/musebots/Updated%20Max%20Externals/Windows/

Thank you for the o.route recommendation.  I'm still wrapping my head around o dot.

**Comment by ramagottfried** [comment]
hi @Splatatat and anyone else who might be interested -- here is a test build for Windows 64bit (and 32bit) -- can you try it and tell me if it loads on your system? 

https://github.com/CNMAT/CNMAT-Externs/releases/tag/v1.0.1_beta.0

So far it's only been tested on Windows 10, so hopefully it will work for you!  please let me know.
