### ISSUE TITLE
bug in resdisplay

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#8]
resdisplay doesn't update its legend (for current range) when the inspector is edited - paint method needs to be called when that value (freqmax, for ex) is changed via the inspector.

i found that re-initializing the object or duplicating it fixes the issue (values are queried upon init)

i'm not sure who is managing stuff like this at this point, so i'm assigning to Adrian in hopes that he'll reassign.

```
    "version" : "Version 6.1.7 (6dce307)",
    "platform" : "mac",
    "arch" : "x86",
    "osversion" : "Mac OS X Version 10.9.4 x86_64",
    "samplerate" : 44100,
    "iovs" : 512,
    "sigvs" : 64,
    "scheduler_in_audio_interrupt" : "off",
    "audio_drivername" : "Core Audio",
    "audio_driver_subname" : "",
    "eventinterval" : 2,
    "overdrive" : "off",
    "mixerparallel" : "off",
    "mixercrossfade" : 0,
    "mixerlatency" : 30.0,
    "mixerramptime" : 10.0,
```

**Comment by ramagottfried** [comment]
the paint routine is called every time -- but currently, the legend displays the *selected* frequency range, not the min/max frequency display values (which are currently not displayed in the GUI). 

It took me a minute to figure that out, so maybe the min/max frequencies should also be drawn in the display, but I'm going to close this issue since that is a design question. @equilet feel free to make a new issue if you think we should display the min/max freq values in the GUI.
