### ISSUE TITLE
CNMAT-Externals object list

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#91]
We've consistently come across issues with a number of objects in the externals release.
Let's build a list of the minimum number of things we're willing to support, evaluating things we people (we know of) rely on, and pair down to our core object set.

My understanding of the most current list is as follows below...
I don't believe we need to support things like interleave if we provide both example code to do it elsewhere, and to push it into the deprecated folder in order to provide minimal support.

```
2threshattack~.mxo
OSC-route.mxo
OSC-schedule.mxo
OSC-timetag.mxo
OpenSoundControl.mxo
SDIF-buffer.mxo
SDIF-fileinfo.mxo
SDIF-info.mxo
SDIF-listpoke.mxo
SDIF-ranges.mxo
SDIF-tuples.mxo
accumulate~.mxo
analyzer~.mxo
bdist.mxo
bench.mxo
bench~.mxo
bessel.mxo
bpf.mxo
cambio~.mxo
cnmatrix~.mxo
decaying-sinusoids~.mxo
deinterleave.mxo
firbank~.mxo
granubuf.mxo
gridpanel.mxo
harmonics~.mxo
interleave.mxo
lcm.mxo
list-accum.mxo
list-interpolate.mxo
migrator.mxo
oscillators~.mxo
peqbank~.mxo
poly.bus~.mxo
poly.send~.mxo
printit.mxo
randdist.mxo
rbfi.mxo
res-transform.mxo
resdisplay.mxo
resonators~.mxo
roughness.mxo
sinusoids~.mxo
slipOSC.mxo
sphY.mxo
thread.fork.mxo
thread.join.mxo
threefates.mxo
trampoline.mxo
trend-report.mxo
vsnapshot~.mxo
waveguide~.mxo
whichthread.mxo
xydisplay.mxo
```

**Comment by adrianfreed** [comment]
Some of those things may break gnu license terms.On Jan 6, 2018 3:24 PM, Jeffrey Lubow <notifications@github.com> wrote:We've consistently come across issues with a number of objects in the externals release.
Let's build a list of the minimum number of things we're willing to support, evaluating things we people (we know of) rely on, and pair down to our core object set.
My understanding of the most current list is as follows below...
I don't believe we need to support things like interleave if we provide both example code to do it elsewhere, and to push it into the deprecated folder in order to provide minimal support.
2threshattack~.mxo
OSC-route.mxo
OSC-schedule.mxo
OSC-timetag.mxo
OpenSoundControl.mxo
SDIF-buffer.mxo
SDIF-fileinfo.mxo
SDIF-info.mxo
SDIF-listpoke.mxo
SDIF-ranges.mxo
SDIF-tuples.mxo
accumulate~.mxo
analyzer~.mxo
bdist.mxo
bench.mxo
bench~.mxo
bessel.mxo
bpf.mxo
cambio~.mxo
cnmatrix~.mxo
decaying-sinusoids~.mxo
deinterleave.mxo
firbank~.mxo
gridpanel.mxo
harmonics~.mxo
interleave.mxo
lcm.mxo
list-accum.mxo
list-interpolate.mxo
migrator.mxo
oscillators~.mxo
peqbank~.mxo
poly.bus~.mxo
poly.send~.mxo
printit.mxo
randdist.mxo
rbfi.mxo
res-transform.mxo
resdisplay.mxo
resonators~.mxo
roughness.mxo
sinusoids~.mxo
slipOSC.mxo
sphY.mxo
thread.fork.mxo
thread.join.mxo
threefates.mxo
trampoline.mxo
trend-report.mxo
vsnapshot~.mxo
waveguide~.mxo
whichthread.mxo
xydisplay.mxo

**Comment by equilet** [comment]
Yes, we are on this question with an evaluation.  Please see other thread for that.

**Comment by equilet** [comment]
https://github.com/CNMAT/CNMAT-Externs/issues/26

**Comment by maccallum** [comment]
I don’t think you can remove interleave, unfortunately. zl lace only does two lists, and I don’t know if relying on mxj is a great idea. I just upgraded to the latest OS and had a ton of Java problems.

**Comment by equilet** [comment]
Thank you - we'll keep interleave in the main release for now.  I was considering moving it to deprecated, but it still seems generally useful.

**Comment by ramagottfried** [comment]
re: interleave -- sounds good, so... maybe we should remove the **"don't use this object!"** message in the help file? : )

re: mxj -- I also did a Java install on Windows the other day which was not as fun as I expected it would be.
